### ISSUE TITLE
Computation of CI for arithmetic mean of beta distributions

### ISSUE THREAD

**Issue by edg-stg** [iqtigorg/iqtigprm#1]
https://github.com/iqtigorg/iqtigprm/blob/084953ff38e72e0b8fdb3afe82ffae9352e751d6/R/compute_results.R#L136

I'm not sure if this is a correct way to calculate a proper credibility interval for the mean of the estimators.
Can you cite a source for this procedure?

E.g. the (mean) sum of multiple beta(0.5,0.5) distributed variables does not look like a similar beta distribution, but has a plateau in the middle. Thus, the CIs become more narrow the more variables are summed over.

**Comment by weidemannf** [comment]
Issue cleared in personal communication.

CI computation is based on sampling for the resulting mean distribution (based on Monte Carlo samples from the underlying beta distributions).
